# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-16 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
