# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20201217_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project1',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
